blogger_blog_homepage_old:
    path:     /hello/{name}
    defaults: { _controller: BloggerBlogBundle:Default:index }

blogger_blog_phphomepage_old:
    path:     /hello/php/{name}
    defaults: { _controller: BloggerBlogBundle:Default:php }

BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
        
BloggerBlogBundle_sidebar:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:sidebar }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+